version: '3'

services:
  web:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: cd backend && python3 manage.py runserver 0.0.0.0:8000
    volumes:
    - .:/code
    ports:
    - "8000:8000"
  node:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
    - "3000:3000"
