version: '3'

services:
  web:
    build: backend/Dockerfile
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
    - .:/code
    ports:
    - "8000:8000"
    node:
      build: frontend/Dockerfile
      ports:
      - "3000:3000"
